### ISSUE TITLE
Dataset is not validating against the CityGML schema; here is how to resolve the issues

### ISSUE THREAD

**Issue by thomashkolbe** [opencitymodel/opencitymodel#1]
Hi, thank your for this great dataset!

However, the files currently do not validate against the CityGML XML schema, due to two problems:
1. The gml:id values are no proper XML ID values, because they start with a digit (which is not allowed) and include a colon (:) which is also not allowed
2. The unit of measure for the building attributed "measuredHeight" is missing.

Both problems can easily be fixed when the entire dataset is loaded into the Open Source 3DCityDB (www.3dcitydb.org) and by running the following three SQL commands:

    update cityobject
        set gmlid=regexp_replace(gmlid,'(\S+):(\S+)','id_\1_\2');
    
    update building
        set measured_height_unit='urn:ogc:def:uom:UCUM::m';
    
    commit;

I tested this using 3DCityDB 4.0 running on an Oracle Spatial database. It should work with PostGIS, too. 
After completion of the commands a full CityGML export could be created which then validates against the schema.

**Comment by agilliland** [comment]
thanks again for the great feedback @thomashkolbe , I've fixed both the format of the gml:id values as well as adding in the uom for the measuredHeight attribute.  the files should all be validating properly now.
