### ISSUE TITLE
Wrong surface orientation

### ISSUE THREAD

**Issue by clausnagel** [opencitymodel/opencitymodel#11]
Thanks for building this great dataset. I downloaded some files and think I spotted a systematic error. The orientation of all roof surfaces seems to be wrong. I made a screenshot of an excerpt of the `Florida-12015-002.gml` dataset using the free [FZKViewer](https://www.iai.kit.edu/english/1302.php). When choosing "Display -> Color -> Face normals" from the main menu, the viewer paints all surfaces having a wrong orientation in red.

![orientation](https://user-images.githubusercontent.com/5517439/51714856-e1cad500-2036-11e9-81d7-aba9aa9310bf.PNG)

When viewed from outside the building shell, the exterior ring of every polygon on the shell must be oriented such that the points are ordered in a counter-clockwise manner (e.g., see [here](http://geovalidation.bk.tudelft.nl/val3dity/docs/errors/#polygon-wrong-orientation)). This rule applies when using solid geometries.

The issue seems to be related to lines 229 and 248 of the `CitygmlBuilder.java` class where both the floor and the roof surface are constructed in the same way. However, for the roof surface, the points from `geometry.getCoordinates()[0]` should be used in a reversed order. Well, at least this is my quick guess how to fix this issue.

**Comment by agilliland** [comment]
Interesting, I had not considered that there was an orientation to the roof surface, but that makes sense.  If it's just a matter of changing the order of the points that make up the polygon then that should be an easy fix.

I'm curious if there are other good ways to validate the CityGML against an issue like this.  This is the kind of thing I'd like to have automatically tested each time we produce new files if possible.

**Comment by hugoledoux** [comment]
there is: https://github.com/tudelft3d/val3dity

**Comment by clausnagel** [comment]
You might also want to look at tools like [CityDoctor](https://www.citydoctor.eu) or [FME](https://www.safe.com/) that offer validation of ISO 19107 geometries in (City)GML files. Personally, I also like to use val3dity. It can be easily integrated into automated tests using its command-line interface. @hugoledoux is the mastermind behind val3dity.

Well, for your LOD1 use case, the algorithm for extruding a 2D polygon to a 3D solid is straightforward. Once you have fixed your code, it should just produce valid solids - given that the input 2D polygon is valid. A large number of errors in 3D models are a consequence of erroneous input data. 

So, I recommend that you also think about adding a validation step for the input data. There are a lot of tools/libraries for validating 2D polygons, and even for fixing certain errors so that you can still produce valid solids. Fixing errors in 3D is a much bigger challenge.

**Comment by agilliland** [comment]
@hugoledoux I'm trying to use `val3dity` to check on some of the new citygml files i'm producing and it's reporting that every single city object is invalid due to `102 -- CONSECUTIVE_POINTS_SAME` but when I manually inspect the geometries such as the one below everything looks fine.  why are these geometries being reported as invalid?

Here's an easy to read layout of the points making up the 6 polygons
```
-- floor
-122.50341869299996 37.72946065200006 0.0 
-122.50348139599998 37.72946065200006 0.0 
-122.50348422399998 37.729577376000066 0.0 
-122.50342152099995 37.72957833400005 0.0 
-122.50341869299996 37.72946065200006 0.0

-- wall 1
-122.50341869299996 37.72946065200006 0.0 
-122.50341869299996 37.72946065200006 8.23 
-122.50348139599998 37.72946065200006 8.23 
-122.50348139599998 37.72946065200006 0.0 
-122.50341869299996 37.72946065200006 0.0

-- wall 2
-122.50348139599998 37.72946065200006 0.0 
-122.50348139599998 37.72946065200006 8.23 
-122.50348422399998 37.729577376000066 8.23 
-122.50348422399998 37.729577376000066 0.0 
-122.50348139599998 37.72946065200006 0.0

-- wall 3
-122.50348422399998 37.729577376000066 0.0 
-122.50348422399998 37.729577376000066 8.23
-122.50342152099995 37.72957833400005 8.23 
-122.50342152099995 37.72957833400005 0.0 
-122.50348422399998 37.729577376000066 0.0

-- wall 4
-122.50342152099995 37.72957833400005 0.0 
-122.50342152099995 37.72957833400005 8.23 
-122.50341869299996 37.72946065200006 8.23 
-122.50341869299996 37.72946065200006 0.0 
-122.50342152099995 37.72957833400005 0.0

-- roof
-122.50341869299996 37.72946065200006 8.23 
-122.50342152099995 37.72957833400005 8.23 
-122.50348422399998 37.729577376000066 8.23 
-122.50348139599998 37.72946065200006 8.23 
-122.50341869299996 37.72946065200006 8.23
```

This is the original GML city object
```xml
<core:cityObjectMember>
    <bldg:Building gml:id="MTBTRUc0Mzc1Oi0xNzk1ODkzMjYz">
      <gen:stringAttribute name="ubid">
        <gen:value>849VPFHW+RJ-0-0-1-0</gen:value>
      </gen:stringAttribute>
      <gen:stringAttribute name="state">
        <gen:value>California</gen:value>
      </gen:stringAttribute>
      <gen:stringAttribute name="county">
        <gen:value>06075</gen:value>
      </gen:stringAttribute>
      <gen:doubleAttribute name="latitude">
        <gen:value>37.729508</gen:value>
      </gen:doubleAttribute>
      <gen:doubleAttribute name="longitude">
        <gen:value>-122.503445</gen:value>
      </gen:doubleAttribute>
      <gen:stringAttribute name="mgrs">
        <gen:value>10SEG4375</gen:value>
      </gen:stringAttribute>
      <gen:doubleAttribute name="area">
        <gen:value>72.04032835321108</gen:value>
      </gen:doubleAttribute>
      <gen:stringAttribute name="height_source">
        <gen:value>msfp-2017</gen:value>
      </gen:stringAttribute>
      <gen:stringAttribute name="fp_source">
        <gen:value>msfp-2017</gen:value>
      </gen:stringAttribute>
      <bldg:measuredHeight uom="urn:ogc:def:uom:UCUM::m">8.23</bldg:measuredHeight>
      <bldg:lod1Solid>
        <gml:Solid>
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon>
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList srsDimension="3">-122.50341869299996 37.72946065200006 0.0 -122.50348139599998 37.72946065200006 0.0 -122.50348422399998 37.729577376000066 0.0 -122.50342152099995 37.72957833400005 0.0 -122.50341869299996 37.72946065200006 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon>
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList srsDimension="3">-122.50341869299996 37.72946065200006 0.0 -122.50341869299996 37.72946065200006 8.23 -122.50348139599998 37.72946065200006 8.23 -122.50348139599998 37.72946065200006 0.0 -122.50341869299996 37.72946065200006 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon>
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList srsDimension="3">-122.50348139599998 37.72946065200006 0.0 -122.50348139599998 37.72946065200006 8.23 -122.50348422399998 37.729577376000066 8.23 -122.50348422399998 37.729577376000066 0.0 -122.50348139599998 37.72946065200006 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon>
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList srsDimension="3">-122.50348422399998 37.729577376000066 0.0 -122.50348422399998 37.729577376000066 8.23 -122.50342152099995 37.72957833400005 8.23 -122.50342152099995 37.72957833400005 0.0 -122.50348422399998 37.729577376000066 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon>
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList srsDimension="3">-122.50342152099995 37.72957833400005 0.0 -122.50342152099995 37.72957833400005 8.23 -122.50341869299996 37.72946065200006 8.23 -122.50341869299996 37.72946065200006 0.0 -122.50342152099995 37.72957833400005 0.0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon>
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList srsDimension="3">-122.50341869299996 37.72946065200006 8.23 -122.50342152099995 37.72957833400005 8.23 -122.50348422399998 37.729577376000066 8.23 -122.50348139599998 37.72946065200006 8.23 -122.50341869299996 37.72946065200006 8.23</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod1Solid>
    </bldg:Building>
  </core:cityObjectMember>
```

**Comment by hugoledoux** [comment]
I need to use a tolerance to snap vertices together. It's mm by default (3
digits after the dot), but since your data are in EPSG:4326 then it's not
correct...

Change it with that option:
http://geovalidation.bk.tudelft.nl/val3dity/docs/usage/#snap-tol

**Comment by agilliland** [comment]
thanks, that was the issue.  oddly though now it's just reporting that every geometry now fails due to the next error, `103 -- RING_NOT_CLOSE`.  clearly a similar type of problem but again i can't seem to see what would be triggering this.  i'm assuming the `--snap_tol -1` setting would also disable the precision rounding for all tests?

**Comment by hugoledoux** [comment]
yes "snap_tol -1" was supposed to disable it, but your case highlighted something I had not thought of, especially that you need like 15 digits after the dot.

I'm fixing it and will get back to you.

However, having lat-long-mixed-with-meters cannot be a good idea for processing anything really. You will encounter many problems, all the time.

**Comment by hugoledoux** [comment]
if you can compile val3dity, the fix is there: https://github.com/tudelft3d/val3dity/commit/8ee42e2d13c79e2dae567e4a76dd51771f567f4b

The option to disable the snap_tol is no more, use a small value. For your data:
just use `snap_tol 0.000000000000001`

**Comment by agilliland** [comment]
perfect.  i recompiled and now the precision of the data points isn't affecting the results.  thanks!
