### ISSUE TITLE
Please offer the files (also) in a zipped format

### ISSUE THREAD

**Issue by thomashkolbe** [opencitymodel/opencitymodel#3]
The CityGML files are offered on the Amazon S3 cloud for download as uncompressed XML files. If you run them through "gzip" or "zip" the filesize will be reduced down to 3% of the original size, which makes downloading much faster.
It would be nice, if you would offer these datasets (and the ones to come) as compressed files.

**Comment by agilliland** [comment]
Thanks for the suggestion Thomas.  We've gone ahead and decided to offer the gml files as zip compressed to make downloading faster and easier.
